// Code generated by goapp_generator. DO NOT EDIT.

package goapp_gpython

import py "github.com/go-python/gpython/py"

// Class: bool, Kind: Value
var _ func(v py.Object) bool = P2G_Bool
var _ func(v bool) py.Object = G2P_Bool

// Class: int, Kind: Value
var _ func(v py.Object) int = P2G_Int
var _ func(v int) py.Object = G2P_Int

// Class: int64, Kind: Value
var _ func(v py.Object) int64 = P2G_Int64
var _ func(v int64) py.Object = G2P_Int64

// Class: float64, Kind: Value
var _ func(v py.Object) float64 = P2G_Float64
var _ func(v float64) py.Object = G2P_Float64

// Class: string, Kind: Value
var _ func(v py.Object) string = P2G_String
var _ func(v string) py.Object = G2P_String

// Class: *errors.errorString, Kind: Value
var _ func(v py.Object) error = P2G_Error
var _ func(v error) py.Object = G2P_Error
